from .product_detail import product_detail
from .product_create import product_create
from .product_update import product_update
from .homepage import homepage
from .product_create import *
from .product_detail import *
from .registration import *
from .search import search
from .signin import signin
from .signout import signout
from .user_detail import user_detail
from .user_lst import user_lst